### ISSUE TITLE
Allow old IAM keys to pass tests via explicit whitelist.

### ISSUE THREAD

**Issue by ian-d** [CU-CloudCollab/cucloud_utils#14]
We have a use case where IAM users exist with keys >90 days old, but their aging is intentional. Either by design or because of the difficulty in rotating the keys. We'd like to explicitly whitelist a list of users in the IAM key age test in automated runs of the resulting cutils image.

A backwards-compatible proposed solution is PR #13.

**Comment by bharanin** [comment]
Thanks for the issue + PR, Ian!

I am curious, what is the use case for not rotating keys?  This set of checks was originally put together to align with ITSO and AWS recommended practices.  If we do merge this, I think it would be important to add context for when whitelisting keys would be acceptable practice...

**Comment by ian-d** [comment]
The use case now is IAM users created strictly for SES / SMTP use, so they keypair is only used for credentialing and using the SMTP endpoint and it's been baked into some applications and vendor configs. The permissions of the user are really narrow in this case.

**Comment by bharanin** [comment]
Thanks - that makes sense - I added some suggested language changes to the PR...
